language: python
cache: pip

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install codecov
  - pip install psycopg2

before_script:
  - cp todoscheduler/settings.py.example todoscheduler/settings.py
  - cp vendor/unicode/categories.json categories.json
  - cp vendor/unicode/confusables.json confusables.json
  - psql -c "CREATE USER todoscheduler WITH ENCRYPTED PASSWORD 'todoscheduler' CREATEDB;" -U postgres

script:
  - flake8
  - coverage run manage.py test

after_success:
  - codecov
