language: python
cache: pip

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install flake8

before_script:
  - cp todoscheduler/settings.py.example todoscheduler/settings.py
  - cp vendor/unicode/categories.json categories.json
  - cp vendor/unicode/confusables.json confusables.json

script:
  - flake8
  - python manage.py test
